# Generated by Django 3.2 on 2021-06-25 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Account',
            new_name='account',
        ),
    ]
