# Generated by Django 3.2 on 2021-06-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210627_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight_starting',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
