# Generated by Django 3.2 on 2021-06-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='type',
        ),
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('chest', 'chest'), ('biceps', 'biceps'), ('triceps', 'triceps'), ('back', 'back'), ('abs', 'abs'), ('leg', 'leg')], max_length=7, null=True),
        ),
    ]
