# Generated by Django 3.2 on 2021-06-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_exercise_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('chest', 'chest'), ('biceps', 'biceps'), ('triceps', 'triceps'), ('back', 'back'), ('abs', 'abs'), ('shoulders', 'shoulders'), ('hamstring', 'hamstring'), ('calves', 'calves'), ('glutes', 'glutes')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight',
            field=models.FloatField(),
        ),
    ]
