# Generated by Django 3.2 on 2021-07-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_training'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='exercises',
        ),
        migrations.AddField(
            model_name='training',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9, null=True),
        ),
    ]
