# Generated by Django 3.2 on 2021-07-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0008_training_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='WEEK_DAY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='training',
            name='day',
        ),
        migrations.AddField(
            model_name='training',
            name='day',
            field=models.ManyToManyField(null=True, to='exercise.WEEK_DAY'),
        ),
    ]
