# Generated by Django 3.2 on 2021-07-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0010_auto_20210711_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='day',
            field=models.ManyToManyField(related_name='day_of_the_week', to='exercise.Day'),
        ),
    ]
