# Generated by Django 3.2 on 2021-07-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0011_alter_training_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='day',
            field=models.ManyToManyField(to='exercise.Day'),
        ),
    ]
