# Generated by Django 3.2 on 2021-07-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0012_alter_training_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='day',
        ),
        migrations.AddField(
            model_name='day',
            name='muscle',
            field=models.ManyToManyField(blank=True, null=True, related_name='day_of_the_week', to='exercise.Training'),
        ),
    ]
