# Generated by Django 3.2 on 2021-07-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0013_auto_20210712_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='muscle',
        ),
        migrations.AddField(
            model_name='training',
            name='day',
            field=models.ManyToManyField(blank=True, null=True, related_name='day_of_the_week', to='exercise.Day'),
        ),
    ]
