# Generated by Django 3.2 on 2021-07-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0014_auto_20210712_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='type',
        ),
        migrations.AddField(
            model_name='training',
            name='muscles',
            field=models.ManyToManyField(to='exercise.Exercise'),
        ),
        migrations.RemoveField(
            model_name='training',
            name='day',
        ),
        migrations.AddField(
            model_name='training',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
