# Generated by Django 3.2 on 2021-07-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0015_auto_20210712_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='muscles',
            field=models.ManyToManyField(related_name='trained_muscle', to='exercise.Exercise'),
        ),
    ]
