# Generated by Django 3.2 on 2021-07-12 21:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercise', '0016_alter_training_muscles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Training',
            new_name='Workout',
        ),
    ]
