# Generated by Django 3.2 on 2021-07-12 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0018_auto_20210712_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='training',
            name='type',
        ),
        migrations.RemoveField(
            model_name='training',
            name='day',
        ),
        migrations.AddField(
            model_name='training',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.day'),
        ),
        migrations.AddField(
            model_name='training',
            name='muscle',
            field=models.ManyToManyField(null=True, to='exercise.Muscle'),
        ),
    ]
