# Generated by Django 3.2 on 2021-07-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0019_auto_20210712_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='muscle',
        ),
        migrations.AddField(
            model_name='training',
            name='exercise',
            field=models.ManyToManyField(null=True, related_name='trained', to='exercise.Exercise'),
        ),
        migrations.DeleteModel(
            name='Muscle',
        ),
    ]
