# Generated by Django 3.2 on 2021-08-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0023_alter_exercise_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='repetition',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='series',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
